import type { SpotterReason } from "./types.ts";

export const SPOTTER_REASON_LABELS: Record<SpotterReason, string> = {
  SPECIAL_LIVERY: "Special Livery",
  RETRO_LIVERY: "Retro Livery",
  ANNIVERSARY_LIVERY: "Anniversary Livery",
  COMMEMORATIVE_LIVERY: "Commemorative Livery",
  PROMOTIONAL_LIVERY: "Promotional Livery",
  ALLIANCE_LIVERY: "Alliance Livery",
  ONE_OFF_LIVERY: "One-off Livery",
  FIRST_OF_TYPE_FOR_AIRLINE: "First of Type",
  LAST_OF_TYPE_FOR_AIRLINE: "Last of Type",
  FIRST_DELIVERED_TO_AIRLINE: "First Delivered to Airline",
  LAST_DELIVERED_TO_AIRLINE: "Last Delivered to Airline",
  FIRST_PRODUCTION_AIRFRAME: "First Production Airframe",
  LAST_PRODUCTION_AIRFRAME: "Last Production Airframe",
  PROTOTYPE: "Prototype Aircraft",
  TEST_AIRCRAFT: "Test Aircraft",
  HISTORICALLY_SIGNIFICANT_AIRFRAME: "Historically Notable",
  OTHER_NOTABLE_HISTORY: "Notable Aircraft History",
  GLOBALLY_UNCOMMON_TYPE: "Globally Uncommon Aircraft",
  GLOBALLY_RARE_TYPE: "Globally Rare Aircraft",
  EXTREMELY_RARE_TYPE: "Exceptionally Rare Aircraft",
  RARE_AT_HOME_AIRPORT: "Rare at ATL",
  VERY_RARE_AT_HOME_AIRPORT: "Very Rare at ATL",
  RARE_VISITOR: "Rare ATL Visitor",
  LONG_ABSENCE: "Long Time Since Last Visit",
  FIRST_RECORDED_VISIT: "First Recorded ATL Visit",
};
